# Generated by Django 5.2.4 on 2025-07-17 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='repaid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TrustRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lend.match')),
            ],
        ),
    ]
