# Generated by Django 5.2.4 on 2025-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0003_match_paid_match_repaid_trustrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
