# Generated by Django 5.2.4 on 2025-07-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallettransaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
